services:
  - type: web
    name: clinic-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://clinic-management-nbnr.onrender.com
